### ISSUE TITLE
下载直接报错，差评

### ISSUE THREAD

**Issue by pin062788** [lemisky/boxuegu#1]
Exception in thread "pool-1-thread-2" net.m3u8.Exception.M3u8Exception: 连接超时！
	at net.m3u8.download.M3u8DownloadFactory$M3u8Download.lambda$4(M3u8DownloadFactory.java:327)
	at java.lang.Thread.run(Thread.java:748)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
已用时28秒！	下载速度：800.154 KB/s

**Comment by lemisky** [comment]
你好，这是json中视频链接失效的原因，请重新拉pa取数据至json文件。


肯定是可以的，有问题请再反馈。

**Comment by lemisky** [comment]
这几天电脑坏了，后面我会抽空将这个错误原因，直接打印提示

**Comment by lemisky** [comment]
你可以试试再反馈
